### ISSUE TITLE
Errno::EINTR: Interrupted system call @ rb_sysopen

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#35]
```
# simple.js
target=UIATarget.localTarget();

target.delay(1);

for (i=0;i<100;i++) {
  target.tapWithOptions({x:135,y:90});
  target.delay(1)
}
```

```
# When targeting iOS 8 GM, the :host strategy will be used.
# Otherwise, :preferences will be used.
moody@stern:~/git/animated-happiness/chou
|2.1.2| (wip/reproduce-UniqueDeviceID-error)
$ be briar console neptune
> start_test_server_in_background({:script => 'simple.js'})
```

The simple.js script runs, but exits with the following:

```
### Stacktrace
2014-09-12 01:37:33 +0200 xcrun instruments -w "89b59706a3ac25e997770a91577ef4e6ad0ab7ba" -D "/var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20140912-71570-1586n6d/trace" -t "Automation" "com.xamarin.chou-cal" -e UIARESULTSPATH /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20140912-71570-1586n6d -e UIASCRIPT /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20140912-71570-1586n6d/_run_loop.js  &> /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20140912-71570-1586n6d/run_loop.out
Errno::EINTR: Interrupted system call @ rb_sysopen - /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20140912-71570-1586n6d/repl-cmd.pipe
    from /Users/moody/git/run-loop/lib/run_loop/core.rb:203:in `initialize'
    from /Users/moody/git/run-loop/lib/run_loop/core.rb:203:in `open'
    from /Users/moody/git/run-loop/lib/run_loop/core.rb:203:in `run_with_options'
    from /Users/moody/git/run-loop/lib/run_loop/core.rb:669:in `run'
    from /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:687:in `block in new_run_loop'
    from /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:685:in `times'
    from /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:685:in `new_run_loop'
    from /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:570:in `relaunch'
    from /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/core.rb:805:in `start_test_server_in_background'
    from (irb):1



### Console Log
ScriptAgent[666] <Warning>: Warning - Unable to stop script because the script was already stopped.
com.apple.xpc.launchd[1] (UIKitApplication:com.xamarin.chou-cal[0x1795][665]) <Notice>: Service exited due to signal: Killed: 9
SpringBoard[43] <Warning>: Unable to get short BSD proc info for 665: No such process
backboardd[56] <Notice>: ALS: SetDisplayFactor: factor=1.0000
SpringBoard[43] <Warning>: Application 'UIKitApplication:com.xamarin.chou-cal[0x1795]' exited abnormally via signal.
assertiond[57] <Warning>: pid_suspend failed for <BKNewProcess: 0x1757b3c0; com.xamarin.chou-cal; pid: 665>: Unknown error: -1, Unknown error: -1
assertiond[57] <Warning>: Could not set priority of <BKNewProcess: 0x1757b3c0; com.xamarin.chou-cal; pid: 665> to 2, priority: No such process
assertiond[57] <Warning>: Could not set priority of <BKNewProcess: 0x1757b3c0; com.xamarin.chou-cal; pid: 665> to 4096, priority: No such process
UserEventAgent[17] <Warning>: id=com.xamarin.chou-cal pid=665, state=0
```

**Comment by majain** [comment]
I solved this issue by fixing my bundle id. There was a typo there on my part and was getting error.
