### ISSUE TITLE
~/ cannot be expanded in some cases - for example RubyMine

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#470]
```
couldn't find HOME environment -- expanding `~' (ArgumentError)
/Library/Ruby/Gems/2.0.0/gems/run_loop-2.1.2/lib/run_loop/device.rb:566:in `expand_path'
/Library/Ruby/Gems/2.0.0/gems/run_loop-2.1.2/lib/run_loop/device.rb:566:in `<class:Device>'
/Library/Ruby/Gems/2.0.0/gems/run_loop-2.1.2/lib/run_loop/device.rb:2:in `<module:RunLoop>'
/Library/Ruby/Gems/2.0.0/gems/run_loop-2.1.2/lib/run_loop/device.rb:1:in `<top (required)>'
```

**Comment by TeresaP** [comment]
Wow, thank you @jmoody! That was quick!
