### ISSUE TITLE
calabash connection is lost as soon as app is launched 

### ISSUE THREAD

**Issue by AshwiniRadha** [calabash/run_loop#510]
```
Admins-Mac-mini:SimpleCreditCardValidator-3 admin$ export DEVICE_ENDPOINT=http://10.16.38.116:37265
Admins-Mac-mini:SimpleCreditCardValidator-3 admin$ export DEVICE_TARGET=3749aff8df3d3f63a9ef20342503e54eea84c227
Admins-Mac-mini:SimpleCreditCardValidator-3 admin$ export BUNDLE_ID=com.xamarin.testcloud.quickstart.SimpleCreditCardValidator
Admins-Mac-mini:SimpleCreditCardValidator-3 admin$ calabash-ios console
Running irb...

#########################  Useful Methods  ##########################
     ids => List all the visible accessibility ids.
  labels => List all the visible accessibility labels.
    text => List all the visible texts.
   marks => List all the visible marks.
    tree => The app's visible view hierarchy.
   flash => flash(<query>); Disco effect for views matching <query>
 verbose => Turn debug logging on.
   quiet => Turn debug logging off.
    copy => Copy console commands to clipboard.
   clear => Clear the console.

Calabash says, "I'm gonna take this to 11."
calabash-ios 0.19.2> start_test_server_in_background
**Calabash::Cucumber::ServerNotRespondingError: Could not connect to the Calabash Server @ http://10.16.38.116:37265.**

See these two guides for help.

* https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices
* https://github.com/calabash/calabash-ios/wiki/Testing-on-iOS-Simulators

1. Make sure your application is linked with Calabash.
2. Make sure there is not a firewall blocking traffic on http://10.16.38.116:37265.
3. Make sure http://10.16.38.116:37265 is correct.

If your app is crashing at launch, find a crash report to determine the cause.


	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/http/http.rb:94:in `raise_on_no_connectivity'
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/http/http.rb:78:in `ensure_connectivity'
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/launcher.rb:345:in `relaunch'
	from /Users/admin/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/core.rb:952:in `start_test_server_in_background'
	from (irb):1
	from /Users/admin/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
calabash-ios 0.19.2> exit
```

**Comment by jmoody** [comment]
> http://10.16.38.116:37265

This is probably incorrect or you haven't linked calabash.framework properly.

* https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices

In particular see:

https://github.com/calabash/calabash-ios/wiki/Testing-on-Physical-Devices#5-verify-your-calabash-ios-version
