### ISSUE TITLE
Expected instruments to report an Automation tracetemplate

### ISSUE THREAD

**Issue by JosNederlof** [calabash/run_loop#552]
I try to start a automatic run with Calabash-iOS, but I encounter a problem that the default_tracetemplate isn't found.
I tried to solve the problem by sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer. It didn't worked.
Is there a solution? 
Here is the output (sorry quit a bit of data):

```
GEMFILE
=======
# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'calabash-cucumber', '~> 0.16.3'
#gem 'calabash-cucumber', '0.20.0'
# gem 'calabash-android', '0.5.14'
gem 'calabash-android', '0.8.0'
# gem 'xamarin-test-cloud', '1.1.2'
gem 'xamarin-test-cloud', '1.1.2'
=========
```

```
MAC0515422:Overheidspocket josnederlof$ bundle install
Using CFPropertyList 2.3.3
Using awesome_print 1.7.0
Using builder 3.2.2
Using diff-lcs 1.2.5
Using multi_json 1.12.1
Using multi_test 0.1.2
Using escape 0.0.4
Using httpclient 2.8.2.4
Using json 1.8.3
Using retriable 2.0.2
Using thor 0.19.1
Using rubyzip 1.2.0
Using calabash-common 0.0.2
Using bundler 1.13.2
Using edn 1.1.1
Using geocoder 1.4.0
Using command_runner_ng 0.1.0
Using rack 1.6.4
Using tilt 2.0.5
Using unf_ext 0.0.7.2
Using mime-types 2.99.3
Using netrc 0.11.0
Using gherkin 2.12.2
Using luffa 2.0.0
Using run_loop 1.5.6
Using rack-protection 1.5.3
Using unf 0.1.4
Using cucumber 1.3.20
Using sinatra 1.4.7
Using domain_name 0.5.20160826
Using slowhandcuke 0.0.3
Using sim_launcher 0.4.13
Using http-cookie 1.0.3
Using calabash-android 0.8.0
Using calabash-cucumber 0.16.4
Using rest-client 1.8.0
Using xamarin-test-cloud 1.1.2
Bundle complete! 3 Gemfile dependencies, 37 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

MAC0515422:Overheidspocket josnederlof$ DEVICE_TARGET='iPhone 6 (9.3)' bundle exec cucumber -p ios
Using the ios profile...
# language: nl
@verdragenbank_doorlopen
Functionaliteit: Als gebruiker van de verdagenbank-app wil ik inloggen en verdragenbankbundels kunnen raadplegen.

  @reinstall
  Scenario: Overheidspocket_doorlopen                                                  # features/overheidspocket_doorlopen.feature:7

INFO: Using uia strategy: 'host'
DEBUG: Searching for run-loop results with glob: /Users/josnederlof/.run-loop/results/*
DEBUG: Found 6 previous run-loop results
DEBUG: Will delete 1 previous run-loop results
DEBUG: Deleted 1 previous results in 0.006346 seconds
DEBUG: Searching for instruments caches with glob: /Library/Caches/com.apple.dt.instruments/xrtmp__*
DEBUG: Found 5 instruments caches
DEBUG: Will delete 0 instruments caches
DEBUG: Deleted 0 instruments caches in 0.000118 seconds
DEBUG: Simulator instruction set 'x86_64' is compatible with '["i386"]'
DEBUG: Launching #<Simulator: iPhone 6 (9.3) 1ABC8D22-28F7-4878-9A5E-300466E790B6 x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 1ABC8D22-28F7-4878-9A5E-300466E790B6
DEBUG: First launch detected - allowing additional time to stabilize
DEBUG: Simulator stable after 20.418746 seconds
DEBUG: Waited a total of 22.418746 seconds for simulator to stabilize
DEBUG: Took 22.434364 seconds to launch the simulator
EXEC: xcrun simctl install 1ABC8D22-28F7-4878-9A5E-300466E790B6 /Users/josnederlof/MCC/Apps/Overheidspocket/opleveringen/OverheidsPocketiOS.app
DEBUG: Simulator stable after 0.38131499999999985 seconds
DEBUG: Waited a total of 2.381315 seconds for simulator to stabilize
DEBUG: Launching #<Simulator: iPhone 6 (9.3) 1ABC8D22-28F7-4878-9A5E-300466E790B6 x86_64> with:
EXEC: xcrun open -g -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 1ABC8D22-28F7-4878-9A5E-300466E790B6
DEBUG: Simulator stable after 14.906973 seconds
DEBUG: Waited a total of 16.906973 seconds for simulator to stabilize
DEBUG: Took 16.987088 seconds to launch the simulator
2016-10-10 08:08:20 +0200 [RunLoop:debug]:
{
                        :app => "/Users/josnederlof/MCC/Apps/Overheidspocket/opleveringen/OverheidsPocketiOS.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/josnederlof/MCC/Apps/Overheidspocket/opleveringen/OverheidsPocketiOS.app",
                  :bundle_id => "nl.rijksoverheid.overheidspocket",
                     :device => "iphone",
              :device_target => "iPhone 6 (9.3)",
                :instruments => #<Instruments 8.0>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/Users/josnederlof/.run-loop/results/2016-10-10_08-07-33/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => true,
                :results_dir => "/Users/josnederlof/.run-loop/results/2016-10-10_08-07-33",
          :results_dir_trace => "/Users/josnederlof/.run-loop/results/2016-10-10_08-07-33/trace",
                     :script => "/Users/josnederlof/.run-loop/results/2016-10-10_08-07-33/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (9.3)",
               :uia_strategy => :host,
                      :xcode => "8.0",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates
 Expected instruments to report an Automation tracetemplate.
 Please report this as bug:  https://github.com/calabash/run_loop/issues
 In the bug report, include the output of:

 $ xcrun xcodebuild -version
 $ xcrun instruments -s templates
  (RuntimeError)
 /Users/josnederlof/.calabash/gems/run_loop-1.5.6/lib/run_loop/core.rb:775:in `default_tracetemplate'
 /Users/josnederlof/.calabash/gems/run_loop-1.5.6/lib/run_loop/core.rb:729:in `automation_template'
 /Users/josnederlof/.calabash/gems/run_loop-1.5.6/lib/run_loop/core.rb:310:in `run_with_options'
 /Users/josnederlof/.calabash/gems/run_loop-1.5.6/lib/run_loop.rb:106:in `run'
 /Users/josnederlof/.calabash/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop'
 /Users/josnederlof/.calabash/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `times'
 /Users/josnederlof/.calabash/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop'
 /Users/josnederlof/.calabash/gems/calabash-cucumber-0.16.4/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
 /Users/josnederlof/MCC/Apps/Overheidspocket/features/ios/support/01_launch.rb:15:in `Before'
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En klik ik op "vraagteken_icoon"                                                          # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Help                                                                # features/step_definitions/overheidspocket_doorlopen_steps.rb:29
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En klik ik op "informatie_icoon"                                                          # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Informatie                                                          # features/step_definitions/overheidspocket_doorlopen_steps.rb:47
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En kies ik toevoegen_nieuwe_pocket                                                        # features/step_definitions/overheidspocket_doorlopen_steps.rb:104
    Dan zie ik het scherm Catalogus                                                           # features/step_definitions/overheidspocket_doorlopen_steps.rb:38
    En kies ik voor "Algemeen" bij veld "Bundeltype"                                          # features/step_definitions/overheidspocket_doorlopen_steps.rb:155
    En klik ik op "Done"                                                                      # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En type ik "woning" in het veld "Titel of omschrijving"                                   # features/step_definitions/overheidspocket_doorlopen_steps.rb:162
    En klik ik op "Zoeken"                                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En klik ik op "zoekloep_icoon"                                                            # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Zoeken                                                              # features/step_definitions/overheidspocket_doorlopen_steps.rb:56
    En type ik "woning" in het veld "zoeken"                                                  # features/step_definitions/overheidspocket_doorlopen_steps.rb:162
    Dan zie ik "Bundel Wijzigingswet" in kolom "Gevonden bundels"                             # features/step_definitions/overheidspocket_doorlopen_steps.rb:144
    En klik ik de eerst gevonden tekst met "Bundel Wijzigingswet" in kolom "Gevonden bundels" # features/step_definitions/overheidspocket_doorlopen_steps.rb:112
    Dan zie ik "Bundel Wijzigingswet" in kolom "Inhoud bundels"                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:144
    En klik ik de eerst gevonden tekst met "Bundel Wijzigingswet" in kolom "Inhoud bundels"   # features/step_definitions/overheidspocket_doorlopen_steps.rb:112
    Dan zie ik "Bundel Wijzigingswet" in kolom "Inhoud verdrag"                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:144
    En tik ik op eerste Lees_direct_button in kolom "Inhoud verdrag"                          # features/step_definitions/overheidspocket_doorlopen_steps.rb:118
    Dan zie ik het scherm Detail                                                              # features/step_definitions/overheidspocket_doorlopen_steps.rb:65
    En klik ik op "bijlage_icoon"                                                             # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan lees ik "Bijlagen"                                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:140
    En klik ik op "bijlage_icoon"                                                             # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En klik ik op "links_icoon"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan lees ik "Links"                                                                       # features/step_definitions/overheidspocket_doorlopen_steps.rb:140
    En klik ik op "links_icoon"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Zoeken                                                              # features/step_definitions/overheidspocket_doorlopen_steps.rb:56
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En kies ik toevoegen_nieuwe_pocket                                                        # features/step_definitions/overheidspocket_doorlopen_steps.rb:104
    Dan zie ik het scherm Catalogus                                                           # features/step_definitions/overheidspocket_doorlopen_steps.rb:38
    En kies ik voor "Decentraal" bij veld "Bundeltype"                                        # features/step_definitions/overheidspocket_doorlopen_steps.rb:155
    En klik ik op "Done"                                                                      # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En klik ik op "Zoeken"                                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En vind ik GegenereerdRedactioneel                                                        # features/step_definitions/overheidspocket_doorlopen_steps.rb:132
    Dan scroll ik naar beneden                                                                # features/step_definitions/overheidspocket_doorlopen_steps.rb:169
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    Dan scroll ik naar beneden                                                                # features/step_definitions/overheidspocket_doorlopen_steps.rb:169
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    Dan scroll ik naar beneden                                                                # features/step_definitions/overheidspocket_doorlopen_steps.rb:169
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    Dan scroll ik naar beneden                                                                # features/step_definitions/overheidspocket_doorlopen_steps.rb:169
    En kies ik Download zoekresultaat                                                         # features/step_definitions/overheidspocket_doorlopen_steps.rb:108
    En klik ik op "Annuleren"                                                                 # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    En klik ik in popup op OK                                                                 # features/step_definitions/overheidspocket_doorlopen_steps.rb:127
    En klik ik op "retour_haak"                                                               # features/step_definitions/overheidspocket_doorlopen_steps.rb:70
    Dan zie ik het scherm Mijn_bibliotheek                                                    # features/step_definitions/overheidspocket_doorlopen_steps.rb:15
    En scroll ik naar volgende bundels                                                        # features/step_definitions/overheidspocket_doorlopen_steps.rb:173

Failing Scenarios:
cucumber -p ios features/overheidspocket_doorlopen.feature:7 # Scenario: Overheidspocket_tablet_doorlopen

1 scenario (1 failed)
66 steps (1 failed, 65 skipped)
0m50.962s

xcrun xcodebuild -version
Xcode 8.0
Build version 8A218a

xcrun instruments -s templates
Known Templates:
"Activity Monitor"
"Allocations"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Log"
"File Activity"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"

ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-darwin15.0]

gem list

*** LOCAL GEMS ***

awesome_print (1.7.0, 1.6.1)
backports (3.6.8)
bigdecimal (1.2.7, 1.2.4)
builder (3.2.2)
bundler (1.13.2, 1.13.1, 1.12.5, 1.12.4, 1.11.2, 1.10.6)
calabash-android (0.8.2, 0.8.1, 0.8.0, 0.7.3, 0.6.0, 0.5.15, 0.5.14)
calabash-common (0.0.2)
calabash-cucumber (0.20.0, 0.19.2, 0.19.1, 0.18.1, 0.17.0, 0.16.4, 0.16.3)
CFPropertyList (2.3.3, 2.3.2)
clipboard (1.1.1, 1.1.0)
command_runner_ng (0.1.0)
cucumber (2.4.0, 1.3.20)
cucumber-core (2.0.0, 1.5.0, 1.4.0, 1.3.1, 1.3.0)
cucumber-wire (0.0.1)
device_detector (0.9.1, 0.9.0, 0.8.2)
diff-lcs (1.2.5)
domain_name (0.5.20160826, 0.5.20160615, 0.5.20160310, 0.5.20160216, 0.5.25)
edn (1.1.1, 1.1.0)
escape (0.0.4)
event-bus (0.2.3, 0.1.0)
geocoder (1.4.0, 1.3.7, 1.3.6, 1.3.4, 1.3.1, 1.3.0, 1.2.14, 1.2.13, 1.2.12, 1.2.11)
gherkin (4.0.0, 3.2.0, 2.12.2)
gherkin3 (3.1.2)
http-cookie (1.0.3, 1.0.2)
httpclient (2.8.2.4, 2.8.2.3, 2.8.0, 2.7.1, 2.7.0.1, 2.6.0.1)
i18n (0.7.0)
io-console (0.4.6, 0.4.5, 0.4.3)
json (2.0.2, 1.8.3, 1.8.1)
luffa (2.0.0)
mime-types (3.1, 3.0, 2.99.3, 2.99.2, 2.6.2)
mime-types-data (3.2016.0521, 3.2016.0221, 3.2015.1120)
minitest (5.9.1, 5.9.0, 5.8.4, 5.8.3, 5.4.3, 4.7.5)
multi_json (1.12.1, 1.11.2)
multi_test (0.1.2)
netrc (0.11.0, 0.10.3)
power_assert (0.3.1, 0.3.0, 0.2.7, 0.2.6, 0.2.2)
psych (2.1.1, 2.1.0, 2.0.17, 2.0.5)
rack (1.6.4)
rack-protection (1.5.3)
rake (11.3.0, 11.2.2, 11.1.2, 10.5.0, 10.4.2, 10.1.0)
rdoc (4.2.2, 4.2.1, 4.1.0)
rest-client (2.0.0, 1.8.0)
retriable (2.1.0, 2.0.2, 1.4.1)
rubyzip (1.2.0, 1.1.7)
run_loop (2.2.1, 2.2.0, 1.5.6)
sim_launcher (0.5.0, 0.4.13)
sinatra (1.4.7, 1.4.6)
slowhandcuke (0.0.3)
test-unit (3.2.1, 3.2.0, 3.1.9, 3.1.7, 3.1.5, 3.0.8, 2.1.7.0)
thor (0.19.1)
tilt (2.0.5, 2.0.4, 2.0.2, 2.0.1)
unf (0.1.4)
unf_ext (0.0.7.2, 0.0.7.1)
xamarin-test-cloud (2.0.2, 2.0.1, 1.1.2)
```

Jos Nederlof

**Comment by jmoody** [comment]
Please use GitHub Markdown formatting: specifically "```"

```
gem 'calabash-cucumber', '~> 0.16.3'
Using run_loop 1.5.6
```

Xcode 8 requires Calabash iOS 0.20.0.

In Xcode 8 there is no Automation template - UIAutomation has been removed.

https://github.com/calabash/calabash-ios/wiki/DeviceAgent
