### ISSUE TITLE
DeviceAgent app install fails on iOS 10.3 (beta)

### ISSUE THREAD

**Issue by Oopla** [calabash/run_loop#601]
I'm trying to execute our test plan on iOS 10.3 (currently at beta3). When using XCode 8.3 beta3, the DeviceAgent fails to install as you can see below:
```
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://192.168.2.34:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://192.168.2.34:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 668e97210c61e41123bdf9bc0c386707dd49bc03 -a /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
Tag: @test

RunLoop::Shell::Error: 
There was an error executing:

/Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 668e97210c61e41123bdf9bc0c386707dd49bc03 -a /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app

The command generated this output:



./features/support/hooks.rb:79:in `some_method'
./features/support/hooks.rb:41:in `Before'
```

If I try to manually install the DeviceAgent-Runner.app using ios-deploy, I get a provisioning profile error:
```
mac test$ ios-deploy -b /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
[....] Waiting for iOS device to be connected
[....] Using iPhone 6 (GSM) 'iPhone' (668e97210c61e41123bdf9bc0c386707dd49bc03).
------ Install phase ------
[  0%] Found iPhone 6 (GSM) 'iPhone' (668e97210c61e41123bdf9bc0c386707dd49bc03) connected through USB, beginning install
[  5%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/META-INF/ to device
[  5%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[  5%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/_CodeSignature/ to device
[  5%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/_CodeSignature/CodeResources to device
[  6%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/embedded.mobileprovision to device
[  6%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/ to device
[  6%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/ to device
[  6%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/_CodeSignature/ to device
[  7%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/_CodeSignature/CodeResources to device
[  7%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/en.lproj/ to device
[  7%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/en.lproj/InfoPlist.strings to device
[  8%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/ to device
[  8%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCAbstractTest.h to device
[  8%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTest.h to device
[  8%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestAssertions.h to device
[  9%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestAssertionsImpl.h to device
[  9%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestCase+AsynchronousTesting.h to device
[  9%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestCase.h to device
[ 10%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestCaseRun.h to device
[ 10%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestDefines.h to device
[ 10%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestErrors.h to device
[ 10%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestExpectation.h to device
[ 11%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestLog.h to device
[ 11%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestObservation.h to device
[ 11%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestObservationCenter.h to device
[ 12%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestObserver.h to device
[ 12%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestProbe.h to device
[ 12%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestRun.h to device
[ 12%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestSuite.h to device
[ 13%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCTestSuiteRun.h to device
[ 13%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIApplication.h to device
[ 13%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUICoordinate.h to device
[ 13%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIDevice.h to device
[ 14%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIElement.h to device
[ 14%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIElementAttributes.h to device
[ 14%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIElementQuery.h to device
[ 15%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIElementTypeQueryProvider.h to device
[ 15%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIElementTypes.h to device
[ 15%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIKeyboardKeys.h to device
[ 15%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Headers/XCUIRemote.h to device
[ 16%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Info.plist to device
[ 16%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Modules/ to device
[ 16%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/Modules/module.modulemap to device
[ 17%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/TextBasedStubs/ to device
[ 17%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/TextBasedStubs/XCTest.tbd to device
[ 17%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/version.plist to device
[ 17%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XCTest to device
[ 23%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XCTest.tbd to device
[ 24%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/ to device
[ 24%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/ to device
[ 24%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/_CodeSignature/ to device
[ 25%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/_CodeSignature/CodeResources to device
[ 25%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/Info.plist to device
[ 25%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/version.plist to device
[ 25%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/xctestSymbolicator.xpc/xctestSymbolicator to device
[ 26%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/ to device
[ 26%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/_CodeSignature/ to device
[ 27%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/_CodeSignature/CodeResources to device
[ 27%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/Info.plist to device
[ 27%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/version.plist to device
[ 27%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework/XPCServices/XCUIRecorderService.xpc/XCUIRecorderService to device
[ 29%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Info.plist to device
[ 29%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PkgInfo to device
[ 29%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/ to device
[ 29%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/ to device
[ 30%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/_CodeSignature/ to device
[ 30%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/_CodeSignature/CodeResources to device
[ 30%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/CBX.xctestconfiguration to device
[ 30%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/CocoaAsyncSocket.LICENSE to device
[ 31%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/CocoaHTTPServer.LICENSE to device
[ 31%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/CocoaLumberjack.LICENSE to device
[ 31%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent to device
[ 39%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/Facebook-WebDriverAgent.LICENSE to device
[ 39%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/Info.plist to device
[ 40%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/LICENSE to device
[ 40%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/RoutingHTTPServer.LICENSE to device
[ 40%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/ to device
[ 40%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/Contents/ to device
[ 41%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/Contents/Info.plist to device
[ 41%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/Contents/Resources/ to device
[ 41%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/Contents/Resources/DWARF/ to device
[ 41%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest.dSYM/Contents/Resources/DWARF/DeviceAgent to device
[ 49%] Copying /Users/test/.rvm/gems/ruby-2.3.0/gems/run_loop-2.3.0/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/XCTRunner to device
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2017-02-22 13:19:10.134 ios-deploy[961:13353] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```

Environment:
macOS 10.12.3
XCode 8.3 beta3
iOS 10.3 beta3
xcode-select -p => /Applications/Xcode-8.3-beta03.app/Contents/Developer

ruby 2.3.0
calabash-cucumber 0.20.4
run_loop 2.3.0

**Comment by jmoody** [comment]
Xcode 8.3 beta is not supported yet.

**Comment by jmoody** [comment]
We will probably wait until Xcode 8.3 master is released - this update is very disruptive.

**Comment by marchv** [comment]
Hi @jmoody :)

I have just updated to Xcode 8.3, which has just been released, and now I get a problem too:

    /Users/username/.rvm/gems/ruby-2.1.2/gems/run_loop-2.2.4/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id ed8b6ed9bde929f5f82e66dbfa2d35757ffb44cb --app-bundle /Users/username/.rvm/gems/ruby-2.1.2/gems/run_loop-2.2.4/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
    Abort trap: 6

Can't find anything related to this in the device console...

**Comment by marchv** [comment]
Update to above: I believe my comment above is not related to iOS 10.3 but more runtime error when running on macOS 10.12.4. Also tried with latest version:

    /Users/username/.rvm/gems/ruby-2.1.2/gems/run_loop-2.3.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id ac45976df6b8e5259efcf1e3b0a6140bdfc42c80 -a /Users/username/.rvm/gems/ruby-2.1.2/gems/run_loop-2.3.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app

**Comment by jmoody** [comment]
This is an Xcode 8.3 problem.  We are working on support.

**Comment by maxelrod** [comment]
Jmoody, can you take a moment to describe the blocking issue?

**Comment by SergiyBeno** [comment]
It is also critical for us to know when exactly we need to expect new release that can handle this issue because of the Swift/Xcode dependencies. Can you spill the beans please ?

**Comment by jmoody** [comment]
> blocking issue

The problem is the FBSimulatorControl, which we depend on for launching DeviceAgent in a privileged state, is having trouble maintaining a stable connection to the testmanagerd process.

We have stabilized Xcode 8.3 for DeviceAgent and iOSDeviceManager by removing the FBSimulatorControl dependency with respect launching DeviceAgent in a privileged state.

The DeviceAgent and iOSDeviceManager have been released and tagged.  The run-loop 2.4.0 release will be done shortly.

https://github.com/calabash/run_loop/pull/613

**Comment by jmoody** [comment]
run-loop 2.2.4 released.

**Comment by marchv** [comment]
Great work @jmoody - it now works again thanks! 👍 
I believe 2.2.4 should be 2.4.0 in above.
BTW: I was using run_loop 2.2.4 before and found it faster. It seems like 2.4.0 reinstall/restart DeviceAgent and this slows it down. But I guess there is a reason for this? Getting better stability?
Have a nice weekend 🤓

**Comment by jmoody** [comment]
2.4.0 should be faster in every way.

The first run with the new gem will always be slower because the new DeviceAgent will need to be installed on the device.
