### ISSUE TITLE
DeviceAgent app crash at start

### ISSUE THREAD

**Issue by Oopla** [calabash/run_loop#621]
Calabash used to work well on my mac but after reinstalling Sierra I cannot launch the automated tests anymore. The DeviceAgent is installed on the phone but it crashes immediately at start.
But it works on another mac I have.

Versions:
macOS: 10.12.5
Xcode: 8.3.2
calabash-ios: 0.20.4
run_loop: 2.4.1

Logs
```
DEVICE_TARGET=01234dc3c08fe1fb23d882cdabea5f6a08e5d789 DEVICE_ENDPOINT=http://192.168.2.2:37271 BUNDLE_ID=com.x.y.z-cal DEBUG=1 bundle exec calabash-ios console
Running irb...
Calabash says, "Enjoy."
calabash-ios 0.20.4> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://192.168.2.2:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://192.168.2.2:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 01234dc3c08fe1fb23d882cdabea5f6a08e5d789 -a /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
DEBUG: Took 9.671047 seconds to install DeviceAgent
SHELL: xcrun xcodebuild test-without-building -xctestrun /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=01234dc3c08fe1fb23d882cdabea5f6a08e5d789 -derivedDataPath /Users/user/.run-loop/DeviceAgent/DerivedData >& /Users/user/.run-loop/DeviceAgent/current.log
DEBUG: HTTP: get http://192.168.2.2:27753/1.0/health {:retries=>1800, :timeout=>180.0}
RuntimeError: 

Could not connect to the DeviceAgent service.

device: #<Device: iPhone (10.2.1) 01234dc3c08fe1fb23d882cdabea5f6a08e5d789>
   url: http://192.168.2.2:27753/

To diagnose the problem tail the launcher log file:

$ tail -1000 -F /Users/user/.calabash/iOSDeviceManager/logs/current.log


	from /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1365:in `rescue in launch_cbx_runner'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1356:in `launch_cbx_runner'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:271:in `launch'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:147:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop.rb:113:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from /Users/user/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from /Users/user/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
calabash-ios 0.20.4>
```

Some more logs
```
2017-06-12 16:37:03.094 DEBUG FBControlCoreLogger:130 | MobileDevice: Loading from /System/Library/PrivateFrameworks/MobileDevice.framework 
2017-06-12 16:37:03.099 DEBUG FBControlCoreLogger:130 | MobileDevice: Successfully loaded
2017-06-12 16:37:03.099 DEBUG FBControlCoreLogger:130 | Loaded All Private Frameworks [MobileDevice]
2017-06-12 16:37:03.273 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftCore.dylib
2017-06-12 16:37:03.273 DEBUG FBControlCoreLogger:130 | Loaded libswiftCore.dylib
2017-06-12 16:37:03.273 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftDarwin.dylib
2017-06-12 16:37:03.273 DEBUG FBControlCoreLogger:130 | Loaded libswiftDarwin.dylib
2017-06-12 16:37:03.275 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftObjectiveC.dylib
2017-06-12 16:37:03.275 DEBUG FBControlCoreLogger:130 | Loaded libswiftObjectiveC.dylib
2017-06-12 16:37:03.275 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftDispatch.dylib
2017-06-12 16:37:03.275 DEBUG FBControlCoreLogger:130 | Loaded libswiftDispatch.dylib
2017-06-12 16:37:03.276 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftIOKit.dylib
2017-06-12 16:37:03.276 DEBUG FBControlCoreLogger:130 | Loaded libswiftIOKit.dylib
2017-06-12 16:37:03.276 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftCoreGraphics.dylib
2017-06-12 16:37:03.276 DEBUG FBControlCoreLogger:130 | Loaded libswiftCoreGraphics.dylib
2017-06-12 16:37:03.278 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftFoundation.dylib
2017-06-12 16:37:03.278 DEBUG FBControlCoreLogger:130 | Loaded libswiftFoundation.dylib
2017-06-12 16:37:03.278 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftXPC.dylib
2017-06-12 16:37:03.278 DEBUG FBControlCoreLogger:130 | Loaded libswiftXPC.dylib
2017-06-12 16:37:03.279 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftCoreImage.dylib
2017-06-12 16:37:03.279 DEBUG FBControlCoreLogger:130 | Loaded libswiftCoreImage.dylib
2017-06-12 16:37:03.279 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftQuartzCore.dylib
2017-06-12 16:37:03.279 DEBUG FBControlCoreLogger:130 | Loaded libswiftQuartzCore.dylib
2017-06-12 16:37:03.280 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftCoreData.dylib
2017-06-12 16:37:03.280 DEBUG FBControlCoreLogger:130 | Loaded libswiftCoreData.dylib
2017-06-12 16:37:03.280 DEBUG FBControlCoreLogger:130 | Attempting to load: /Applications/Xcode-8.3.2.app/Contents/Frameworks/libswiftAppKit.dylib
2017-06-12 16:37:03.280 DEBUG FBControlCoreLogger:130 | Loaded libswiftAppKit.dylib
2017-06-12 16:37:03.280 DEBUG FBControlCoreLogger:130 | DTXConnectionServices: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DTXConnectionServices.framework 
2017-06-12 16:37:03.282 DEBUG FBControlCoreLogger:130 | DTXConnectionServices: Successfully loaded
2017-06-12 16:37:03.282 DEBUG FBControlCoreLogger:130 | DTXConnectionServices: DTXConnection has correct path of /Applications/Xcode-8.3.2.app
2017-06-12 16:37:03.282 DEBUG FBControlCoreLogger:130 | DTXConnectionServices: DTXRemoteInvocationReceipt has correct path of /Applications/Xcode-8.3.2.app
2017-06-12 16:37:03.282 DEBUG FBControlCoreLogger:130 | IDEFoundation: Loading from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEFoundation.framework 
2017-06-12 16:37:03.342 DEBUG FBControlCoreLogger:130 | IDEFoundation: Successfully loaded
2017-06-12 16:37:03.342 DEBUG FBControlCoreLogger:130 | IDEFoundation: IDEFoundationTestInitializer has correct path of /Applications/Xcode-8.3.2.app
2017-06-12 16:37:03.342 DEBUG FBControlCoreLogger:130 | DevToolsFoundation: Loading from /Applications/Xcode-8.3.2.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsFoundation.framework 
2017-06-12 16:37:03.344 DEBUG FBControlCoreLogger:130 | DevToolsFoundation: Successfully loaded
2017-06-12 16:37:03.344 DEBUG FBControlCoreLogger:130 | DevToolsSupport: Loading from /Applications/Xcode-8.3.2.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsSupport.framework 
2017-06-12 16:37:03.347 DEBUG FBControlCoreLogger:130 | DevToolsSupport: Successfully loaded
2017-06-12 16:37:03.347 DEBUG FBControlCoreLogger:130 | DevToolsCore: Loading from /Applications/Xcode-8.3.2.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework 
2017-06-12 16:37:03.353 DEBUG FBControlCoreLogger:130 | DevToolsCore: Successfully loaded
2017-06-12 16:37:03.353 DEBUG FBControlCoreLogger:130 | IDEiOSSupportCore: Loading from /Applications/Xcode-8.3.2.app/Contents/PlugIns/IDEiOSSupportCore.ideplugin 
2017-06-12 16:37:03.364 DEBUG FBControlCoreLogger:130 | IDEiOSSupportCore: Successfully loaded
2017-06-12 16:37:03.366 DEBUG FBControlCoreLogger:130 | IDEiOSSupportCore: DVTiPhoneSimulator has correct path of /Applications/Xcode-8.3.2.app
2017-06-12 16:37:03.366 DEBUG FBControlCoreLogger:130 | IBAutolayoutFoundation: Loading from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IBAutolayoutFoundation.framework 
2017-06-12 16:37:03.369 DEBUG FBControlCoreLogger:130 | IBAutolayoutFoundation: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IBAutolayoutFoundation.framework, attempting to find the Framework name
2017-06-12 16:37:03.369 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework IBFoundation.framework
2017-06-12 16:37:03.369 DEBUG FBControlCoreLogger:130 | IBFoundation: Loading from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IBFoundation.framework 
2017-06-12 16:37:03.377 DEBUG FBControlCoreLogger:130 | IBFoundation: Successfully loaded
2017-06-12 16:37:03.377 DEBUG FBControlCoreLogger:130 | IBFoundation.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks', re-attempting to load IBAutolayoutFoundation
2017-06-12 16:37:03.379 DEBUG FBControlCoreLogger:130 | IBAutolayoutFoundation: Successfully loaded
2017-06-12 16:37:03.380 DEBUG FBControlCoreLogger:130 | IDEKit: Loading from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEKit.framework 
2017-06-12 16:37:03.384 DEBUG FBControlCoreLogger:130 | IDEKit: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEKit.framework, attempting to find the Framework name
2017-06-12 16:37:03.384 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework DVTProducts.framework
2017-06-12 16:37:03.384 DEBUG FBControlCoreLogger:130 | DVTProducts.framework could not be loaded from fallback directory /Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks
2017-06-12 16:37:03.384 DEBUG FBControlCoreLogger:130 | DVTProducts: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DVTProducts.framework 
2017-06-12 16:37:03.386 DEBUG FBControlCoreLogger:130 | DVTProducts: Successfully loaded
2017-06-12 16:37:03.386 DEBUG FBControlCoreLogger:130 | DVTProducts.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../SharedFrameworks', re-attempting to load IDEKit
2017-06-12 16:37:03.388 DEBUG FBControlCoreLogger:130 | IDEKit: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEKit.framework, attempting to find the Framework name
2017-06-12 16:37:03.388 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework DADocSetManagement.framework
2017-06-12 16:37:03.388 DEBUG FBControlCoreLogger:130 | DADocSetManagement.framework could not be loaded from fallback directory /Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks
2017-06-12 16:37:03.388 DEBUG FBControlCoreLogger:130 | DADocSetManagement: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DADocSetManagement.framework 
2017-06-12 16:37:03.390 DEBUG FBControlCoreLogger:130 | DADocSetManagement: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DADocSetManagement.framework, attempting to find the Framework name
2017-06-12 16:37:03.390 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework DADocSetAccess.framework
2017-06-12 16:37:03.390 DEBUG FBControlCoreLogger:130 | DADocSetAccess.framework could not be loaded from fallback directory /Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks
2017-06-12 16:37:03.390 DEBUG FBControlCoreLogger:130 | DADocSetAccess: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DADocSetAccess.framework 
2017-06-12 16:37:03.393 DEBUG FBControlCoreLogger:130 | DADocSetAccess: Successfully loaded
2017-06-12 16:37:03.393 DEBUG FBControlCoreLogger:130 | DADocSetAccess.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../SharedFrameworks', re-attempting to load DADocSetManagement
2017-06-12 16:37:03.394 DEBUG FBControlCoreLogger:130 | DADocSetManagement: Successfully loaded
2017-06-12 16:37:03.394 DEBUG FBControlCoreLogger:130 | DADocSetManagement.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../SharedFrameworks', re-attempting to load IDEKit
2017-06-12 16:37:03.397 DEBUG FBControlCoreLogger:130 | IDEKit: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEKit.framework, attempting to find the Framework name
2017-06-12 16:37:03.397 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework DVTDeveloperModeHelper.framework
2017-06-12 16:37:03.397 DEBUG FBControlCoreLogger:130 | DVTDeveloperModeHelper.framework could not be loaded from fallback directory /Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks
2017-06-12 16:37:03.397 DEBUG FBControlCoreLogger:130 | DVTDeveloperModeHelper: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DVTDeveloperModeHelper.framework 
2017-06-12 16:37:03.398 DEBUG FBControlCoreLogger:130 | DVTDeveloperModeHelper: Successfully loaded
2017-06-12 16:37:03.398 DEBUG FBControlCoreLogger:130 | DVTDeveloperModeHelper.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../SharedFrameworks', re-attempting to load IDEKit
2017-06-12 16:37:03.401 DEBUG FBControlCoreLogger:130 | IDEKit: Bundle could not be loaded from /Applications/Xcode-8.3.2.app/Contents/Frameworks/IDEKit.framework, attempting to find the Framework name
2017-06-12 16:37:03.401 DEBUG FBControlCoreLogger:130 | Attempting to load missing framework DTGraphKit.framework
2017-06-12 16:37:03.401 DEBUG FBControlCoreLogger:130 | DTGraphKit.framework could not be loaded from fallback directory /Applications/Xcode-8.3.2.app/Contents/Developer/../Frameworks
2017-06-12 16:37:03.401 DEBUG FBControlCoreLogger:130 | DTGraphKit: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DTGraphKit.framework 
2017-06-12 16:37:03.403 DEBUG FBControlCoreLogger:130 | DTGraphKit: Successfully loaded
2017-06-12 16:37:03.403 DEBUG FBControlCoreLogger:130 | DTGraphKit.framework has been loaded from fallback directory '/Applications/Xcode-8.3.2.app/Contents/Developer/../SharedFrameworks', re-attempting to load IDEKit
2017-06-12 16:37:03.417 DEBUG FBControlCoreLogger:130 | IDEKit: Successfully loaded
2017-06-12 16:37:03.417 DEBUG FBControlCoreLogger:130 | IDESourceEditor: Loading from /Applications/Xcode-8.3.2.app/Contents/PlugIns/IDESourceEditor.ideplugin 
2017-06-12 16:37:03.421 DEBUG FBControlCoreLogger:130 | IDESourceEditor: Successfully loaded
2017-06-12 16:37:03.421 DEBUG FBControlCoreLogger:130 | DFRSupportKit: Loading from /Applications/Xcode-8.3.2.app/Contents/Frameworks/DFRSupportKit.framework 
2017-06-12 16:37:03.422 DEBUG FBControlCoreLogger:130 | DFRSupportKit: Successfully loaded
2017-06-12 16:37:03.422 DEBUG FBControlCoreLogger:130 | DVTKit: Loading from /Applications/Xcode-8.3.2.app/Contents/SharedFrameworks/DVTKit.framework 
2017-06-12 16:37:03.422 DEBUG FBControlCoreLogger:130 | DVTKit: Successfully loaded
2017-06-12 16:37:03.422 DEBUG FBControlCoreLogger:130 | Loaded All Private Frameworks [DTXConnectionServices, IDEFoundation, IDEiOSSupportCore, IBAutolayoutFoundation, IDEKit, IDESourceEditor, DFRSupportKit, DVTKit]
2017-06-12 16:37:09.001 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.036 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security find-identity -v -p codesigning
2017-06-12 16:37:09.104 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/60d58e6f-dd7f-458c-b480-690270571586.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/6D091750-63C0-470E-9B72-35909A62CA08-13323-0005D6B6C45F6985.plist
2017-06-12 16:37:09.104 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/bc46aa11-1786-41b2-abb4-783948300d74.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/B5F5CEDD-5FFF-422B-97D1-7384D3F33610-13323-0005D6B6C45F913C.plist
2017-06-12 16:37:09.104 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/c89c11da-4303-47f2-b2ee-c6198a706ee2.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/B473DB13-DA58-4652-BC08-D037E53BF849-13323-0005D6B6C45FD359.plist
2017-06-12 16:37:09.165 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/60d58e6f-dd7f-458c-b480-690270571586.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/666E3714-0793-4F61-9458-AF0FD1F04940-13323-0005D6B6C7FCB824.plist
2017-06-12 16:37:09.165 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/bc46aa11-1786-41b2-abb4-783948300d74.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/16CBE907-19CB-4676-9580-604A6BD4DC1F-13323-0005D6B6C7FD5C62.plist
2017-06-12 16:37:09.165 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/c89c11da-4303-47f2-b2ee-c6198a706ee2.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/88D14962-1751-47E5-97C7-8EBECE4D75E5-13323-0005D6B6C7FD6F9B.plist
2017-06-12 16:37:09.228 INFO ConsoleWriter:22 | Using signing identity #<CodesignIdentity: 0D7722493A4829B74AB66E84400E42F414981234 : iPhone Developer: XXX YYY (ZZZZZZZZZ)> to select best match profile.
2017-06-12 16:37:09.228 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/60d58e6f-dd7f-458c-b480-690270571586.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/73B35D32-ACCE-46CC-800B-6D709E1086C8-13323-0005D6B6CBC03B49.plist
2017-06-12 16:37:09.228 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/bc46aa11-1786-41b2-abb4-783948300d74.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/60DDD32B-F4F3-4D91-8162-3FED811FC31A-13323-0005D6B6CBC04B3D.plist
2017-06-12 16:37:09.228 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security cms -D -i /Users/user/Library/MobileDevice/Provisioning Profiles/c89c11da-4303-47f2-b2ee-c6198a706ee2.mobileprovision -o /var/folders/kb/rq9wznl90z9bykrnhtkmyl0w0000gn/T/85D15A3A-881B-4DEA-8392-C19B6E04F6AF-13323-0005D6B6CBC080E6.plist
2017-06-12 16:37:09.289 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.322 INFO ConsoleWriter:22 | Selected profile #<MobileProfile iOS  <abc temp> expired: NO rank: 4> for device 01234dc3c08fe1fb23d882cdabea5f6a08e5d789 app com.apple.test.DeviceAgent-Runner
2017-06-12 16:37:09.322 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun security find-identity -v -p codesigning
2017-06-12 16:37:09.389 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.420 INFO ConsoleWriter:22 | Preparing to resign bundle DeviceAgent-Runner.app with profile abc inhouse - DEV
2017-06-12 16:37:09.422 INFO ConsoleWriter:22 | Original entitlements:
2017-06-12 16:37:09.423 INFO ConsoleWriter:22 | #<Entitlements: {
  "keychain-access-groups" : [
    "AB123CDEF4.*"
  ],
  "com.apple.developer.team-identifier" : "AB123CDEF4",
  "application-identifier" : "AB123CDEF4.x.y.z.tmp",
  "get-task-allow" : true
}>
2017-06-12 16:37:09.423 INFO ConsoleWriter:22 | New Entitlements
2017-06-12 16:37:09.423 INFO ConsoleWriter:22 | #<Entitlements: {
  "get-task-allow" : true,
  "com.apple.developer.team-identifier" : "AB123CDEF4",
  "application-identifier" : "AB123CDEF4.x.y.z.tmp",
  "keychain-access-groups" : [
    "AB123CDEF4.*"
  ]
}>
2017-06-12 16:37:09.423 INFO ConsoleWriter:22 | Resigning to new teamID: AB123CDEF4
2017-06-12 16:37:09.425 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.457 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.489 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.520 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.551 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.582 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.614 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.645 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign --force --sign 0D7722493A4829B74AB66E84400E42F414981234 --verbose=4 --deep /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.823 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.855 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/Frameworks/XCTest.framework
2017-06-12 16:37:09.887 INFO ConsoleWriter:22 | Codesigned XCTest.framework: 'TeamIdentifier=AB123CDEF4' => 'TeamIdentifier=AB123CDEF4'
2017-06-12 16:37:09.887 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.919 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:09.950 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign --force --sign 0D7722493A4829B74AB66E84400E42F414981234 -vv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/XCTRunner --entitlements /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/DeviceAgent-Runner.xcent /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:10.278 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:10.310 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d -vvv /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:10.341 INFO ConsoleWriter:22 | Codesigned DeviceAgent-Runner.app: 'TeamIdentifier=AB123CDEF4' => 'TeamIdentifier=AB123CDEF4'
2017-06-12 16:37:10.341 INFO ConsoleWriter:22 | Done resigning DeviceAgent-Runner.app with abc inhouse - DEV.
2017-06-12 16:37:10.341 INFO ShellRunner:70 | EXEC: /usr/bin/xcrun codesign -d --entitlements :- /Users/user/.rvm/gems/ruby-2.3.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
2017-06-12 16:37:10.373 ERROR ConsoleWriter:32 | Checking for profile and app entitlement discrepancy
```

**Comment by Oopla** [comment]
Fixed by reinstall macOS 10.12.6
