### ISSUE TITLE
DeviceAgent does not dismiss APNS springboard alert automatically in portuguese (pt-BR) when running on physical devices

### ISSUE THREAD

**Issue by klemachado** [calabash/run_loop#624]
When trying to execute a query on console, using a physical device, I am getting an error message: 

MacOS: Sierra 10.12.5
Xcode: 8.3.3
xcodebuild -version: Xcode 8.3.3 Build version 8E3004b
Calabash: 0.20.5
Run_loop: 2.4.1
Device: Iphone 7 (10.3.2)

```
kleberm@MACCIT012705 specs-pf (develop) $ DEBUG=1 bundle exec calabash-ios console
Running irb...

#########################  Useful Methods  ##########################
     ids => List all the visible accessibility ids.
  labels => List all the visible accessibility labels.
    text => List all the visible texts.
   marks => List all the visible marks.
    tree => The app's visible view hierarchy.
   flash => flash(<query>); Disco effect for views matching <query>
 verbose => Turn debug logging on.
   quiet => Turn debug logging off.
    copy => Copy console commands to clipboard.
   clear => Clear the console.

Calabash says, "Console. Engaged."
calabash-ios 0.20.5> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://172.16.57.107:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://172.16.57.107:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 014cbda337ce9a65b7c208ce8a013bea3223e1af -a /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
DEBUG: Took 16.226733 seconds to install DeviceAgent
SHELL: xcrun xcodebuild test-without-building -xctestrun /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=014cbda337ce9a65b7c208ce8a013bea3223e1af -derivedDataPath /Users/kleberm/.run-loop/DeviceAgent/DerivedData >& /Users/kleberm/.run-loop/DeviceAgent/current.log
DEBUG: HTTP: get http://172.16.57.107:27753/1.0/health {:retries=>1800, :timeout=>180.0}
DEBUG: DeviceAgent says, "Calabash is ready and waiting."
DEBUG: Took 22.22248 launch and respond to /health
DEBUG: HTTP: post http://172.16.57.107:27753/1.0/session {:retries=>200, :timeout=>20}
DEBUG: Launched com.xxxx.enterprise.yyyy on #<Device: Fury - iPhone 7 (10.3.2) 014cbda337ce9a65b7c208ce8a013bea3223e1af>
DEBUG: {"status":"launched!"}
DEBUG: Took 22.824808 seconds to launch com.xxxx.enterprise.yyyy on #<Device: Fury - iPhone 7 (10.3.2) 014cbda337ce9a65b7c208ce8a013bea3223e1af>
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Trying to connect to Calabash Server: 2 of 10
DEBUG: Connected to Calabash Server on try: 2 of 10
DEBUG: Trying to connect to Calabash Server: 1 of 10
DEBUG: Connected to Calabash Server on try: 1 of 10
#<Launcher: DeviceAgent/ios_device_manager>
calabash-ios 0.20.5> ids
DEBUG: HTTP: post http://172.16.57.107:27753/1.0/dismiss-springboard-alerts {:retries=>200, :timeout=>20}
RunLoop::DeviceAgent::Client::HTTPError: 
Expected status code < 400, found 500.

Server replied with:

{"title"=>”“XXXX” Deseja Enviar Notificações", "buttons"=>["Não Permitir", "Permitir"], "tries"=>20, "error"=>"A SpringBoard alert is blocking test execution and it cannot be dismissed."}


	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1498:in `expect_300_response'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1599:in `_dismiss_springboard_alerts'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/http_helpers.rb:118:in `_private_dismiss_springboard_alerts'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/http_helpers.rb:22:in `http'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/map.rb:88:in `raw_map'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/map.rb:58:in `map'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/core.rb:149:in `query'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/console_helpers.rb:190:in `accessibility_marks'
	from /Users/kleberm/.rvm/gems/ruby-2.3.3@super_app_pf/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/console_helpers.rb:15:in `ids'
	from (irb):2
	from /Users/kleberm/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
calabash-ios 0.20.5>
```

**Comment by jmoody** [comment]
I have captured this as an internal issue.  The next release of DeviceAgent will contain this change.

Thanks for reporting.

**Comment by klemachado** [comment]
Thank you very much !

**Comment by jmoody** [comment]
Should be in the released version of run-loop.

**Comment by seshusangeetha** [comment]
Hi,

I am also faced with similar error indicating that it is unable to handle the spring board alert. While the run_loop I use is 2.6.3 . Does this include the fix? kindly let me know how can I handle this alert so as to run my tests successfully. Because I am unable to handle it to run my automation scripts as it is responding with the similar error when I try to query with the help of device agent. Kindly let me know the solution because I am blocked tasks because of this.

Thanks

**Comment by jmoody** [comment]
>  handle the spring board alert. 

What SpringBoard alert.  Please paste the error message.

If your problem is not with pt-BR and APNS, please open a new issue.

To make progress, follow these instructions.

```
...
# Turn off automatic alert dismissal
device_agent.dismiss_springboard_alerts_manually!

# Do whatever triggers the alert, then wait for the alert
# which may or may not appear.
begin
  device_agent.wait_for_springboard_alert(10) # timeout is optional
  device_agent.dismiss_springboard_alert("OK")
rescue RuntimeError
   # Alert did not appear, so there is nothing to do
end
...

# Turn automatic dismiss back on
dismiss_springboard_alerts_automatically!
```

**Comment by emrah-dautbegovic-sleepnumber** [comment]
Hi, I faced a similar issue. Device language is Croatian and DeviceAgent cannot automatically accept native iOS pop up. I changed device language to English and it works :) :) :)

**Comment by jmoody** [comment]
Shortly after Xcode 11 is released, we will release a DeviceAgent that can dismiss almost any alert in every supported language.
