### ISSUE TITLE
DeviceAgent not launching in iOS 11 beta 3

### ISSUE THREAD

**Issue by abardallis** [calabash/run_loop#626]
Does calabash-ios support the iOS 11 beta 3 or not yet?

iOS 11.0 beta 3
Xcode 9.0 beta 3
calabash-ios 0.20.5
ruby 2.3.4
run-loop 2.4.1

When launching the calabash-console, it doesn't appear that the DeviceAgent app is being installed. After installing manually via ios-deploy, I'm still seeing the same issue with a timeout while waiting for DeviceAgent to launch.

```
calabash-ios 0.20.5> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://10.121.53.50:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://10.121.53.50:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 900be7c83c163c22603ce0b0922ac96bfb5184d7 -a /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
RunLoop::Shell::TimeoutError: 
Timed out after 120.08 seconds executing

/Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 900be7c83c163c22603ce0b0922ac96bfb5184d7 -a /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app

with a timeout of 120

	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/shell.rb:104:in run_shell_command'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/ios_device_manager.rb:139:in `launch'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1354:in `launch_cbx_runner'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:271:in `launch'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:147:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/run_loop-2.4.1/lib/run_loop.rb:113:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from /Users/user/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from /Users/user/.rvm/rubies/ruby-2.3.4/bin/irb:11:in `<main>'
```

**Comment by jmoody** [comment]
run-loop 2.5.2 has preliminary Xcode 9 beta 6 support.
