### ISSUE TITLE
:host strategy is hanging intermittently on iOS 7 device

### ISSUE THREAD

**Issue by jmoody** [calabash/run_loop#99]
#### Stack

* Yosemite 10.10.2
* Xcode 6.1.1

#### Reproduce

1. In briar's support/01_launch.rb, set the strategy to :host.
2. Run the entire suite.

#### Expected 

All the tests to execute.

#### Found

Several times, cucumber stopped indefinitely.

* The app launched.
* Sometimes no Steps were executed.
* Sometimes, the hang occurred in the middle of Scenario.

In Activity Monitor, I found the instruments process was not responding.  After force quitting instruments, I found the following output.

```
  Interrupted system call @ rb_sysopen - /var/folders/bx/5wplnzxx7492fynry0m_hw080000gp/T/run_loop20150105-10325-1u8mcwr/repl-cmd.pipe (Errno::EINTR)
  /Users/moody/git/run-loop/lib/run_loop/core.rb:259:in `initialize'
  /Users/moody/git/run-loop/lib/run_loop/core.rb:259:in `open'
  /Users/moody/git/run-loop/lib/run_loop/core.rb:259:in `run_with_options'
  /Users/moody/git/run-loop/lib/run_loop/core.rb:793:in `run'
  /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:732:in `block in new_run_loop'
  /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:730:in `times'
  /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:730:in `new_run_loop'
  /Users/moody/git/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:605:in `relaunch'
  /Users/moody/git/briar-ios-example/Briar/features/support/01_launch.rb:27:in `Before'
```

I captured run_loop.out in a gist.

* https://gist.github.com/jmoody/dd610904d8d0926a4e21

**Comment by jmoody** [comment]
Possibly due to a stale .bundle file in my local repo that was forcing the use of an old pre-release version of calabash-ios.
